language: android

android:
  components:
    - build-tools-28.0.3
    - android-29
    - android-26
    - android-25
    - android-23
  licenses:
    - 'android-sdk-license-.+'

before_script:
  - ./gradlew assemble

script:
  - ./gradlew check

jdk:
  - oraclejdk8
